# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf2f2fa5bc0ce0cd21c980a2ee47b63ad7ece7c360614e70e8d5b6a81b7ed44e8f3b867d2f5327913813efe004c844a706b66f852e9d8b5e154a702a032a075

test:
  secret_key_base: b4f8da3803ddd0f30d9e6819cecd7288fb92cf9bec0435736838e615bd0342f2f9afc832a2445a2c6cf69eeb9a0e01cf5e3eb000959b9453a567eb58665607ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
